### ISSUE TITLE
windows defender report trojan:scrpit threaten

### ISSUE THREAD

**Issue by ruohai** [memospot/memos-builds#78]
### Describe the bug

windows defender on window 10  report trojan script threaten while download the [memos-v0.17.1-linux-armv7l.tar.gz](https://github.com/memospot/memos-builds/releases/download/v0.17.1/memos-v0.17.1-linux-armv7l.tar.gz)

![Snipaste_2024-07-28_19-35-40](https://github.com/user-attachments/assets/ae6a4e1a-cf67-48d6-b907-6bc390f34743)
![Snipaste_2024-07-28_19-35-52](https://github.com/user-attachments/assets/ee91d00a-579d-4c9c-b3d0-59da442c41ab)

### Steps to reproduce

go to realease page and choose download the armv7l package , when it downlaoded my pc will report a torjan worm security alert。

**Comment by lincolnthalles** [comment]
Unless your machine has been tampered with, it's a false-positive. You can confirm that the tar file is unaltered by checking the sha256 hash against the `memos_SHA256SUMS.txt` file, available for each release.

Linux builds use [UPX](https://github.com/upx/upx) compression in the final build stage, which reduces the binary from ~46 to ~9 MB, but in return, that increases the false-positive rates, as stated in [Notes](https://github.com/memospot/memos-builds#notes).

Also, many antivirus software are known to flag files simply due to low circulation and lack of Code Signing Certificates, which are expensive to maintain.

You should submit any suspicious files to https://www.virustotal.com or https://virusscan.jotti.org, and worry only if several major vendors flag the file.

That very same file from `memos-v0.17.1-linux-armv7l.tar.gz` gets [2 flags](https://www.virustotal.com/gui/file/b8b6b0da4287dc1c4162ea152038501d614a5aaac641f6ebbe417c9a551d95ef) in VirusTotal, but they go away after decompressing the file with `upx -d memos´, and the file gets [marked as clean](https://www.virustotal.com/gui/file/17885a29fe4c4eab60a4ab10cd88ce1e74e8bc38aabd2f19f4e67823b8bf8b3c) by 67 different AV software.
